import Head from 'next/head'
import Wardrobe from './wardrobe'
import Info from './info'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>WeatherWear</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.icon" />
      </Head>
      <div className='home-text'>
        <h1 className={styles.title}>WeatherWear</h1>
        <p className='home-description'>the bridge between style and comfort.</p>
      </div>
    </>
  )
}
